# Generated by Django 4.1.7 on 2023-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='status',
        ),
        migrations.AlterField(
            model_name='librarian',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
