# Generated by Django 4.1.7 on 2023-02-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_remove_bookorder_book_bookorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookorderdetail',
            name='count',
        ),
    ]
