# Generated by Django 4.1.7 on 2023-02-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_bookissue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='status',
            field=models.CharField(choices=[('REQ', 'requested'), ('DEN', 'denied'), ('PRG', 'progress'), ('DON', 'done')], default='REQ', max_length=20),
        ),
    ]
