# Generated by Django 4.1.7 on 2023-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_alter_bookissue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='status',
            field=models.CharField(choices=[('OPN', 'open'), ('CAN', 'cancelled'), ('PRG', 'progress'), ('DON', 'done')], default='OPN', max_length=100),
        ),
    ]
